<?php

use Illuminate\Database\Seeder;

class ModuleVersionSeederTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [];

        //for android
        $data[] = ['module_name'=>'Home','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Explore','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Reviews','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Chat','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Settings','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Profile','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Private-Collaborate','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Collaborate','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Notification','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Onboarding','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Company','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Private-Collaborate-Review','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Overall','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Public-Review','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Public-Review-Process','compatible_version'=>'42','latest_version'=>'42','platform'=>'android','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];

        //for ios
        $data[] = ['module_name'=>'Home','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Explore','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Reviews','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Chat','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Settings','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Profile','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Private-Collaborate','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Collaborate','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Notification','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Onboarding','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Company','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Private-Collaborate-Review','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Overall','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Public-Review','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];
        $data[] = ['module_name'=>'Public-Review-Process','compatible_version'=>'3.0.1','latest_version'=>'3.0.1','platform'=>'ios','title'=>"Please, update app to new version to continue reposting.","description"=>"Store the versionCode of your app(which you have released on the playstore) on the server side. Hit the API every time user opens the app and get the versionCode. Compare the versionCode of the app user is currently using and the one you have stored on the server"];

        \DB::table('module_versions')->insert($data);

    }
}
